### ISSUE TITLE
Lost sorting on scan results.

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-server#114]
## Description
With the switch from python to golang we have lost the sorting on scan results.

We used to output devices in config order.

This may not be the biggest deal, but it something to note.
## Related Issues
- 

## Close Criteria
-

**Comment by edaniszewski** [comment]
Is sorting on scan results something we want to have? We didn't guarantee it in 1.4. The rack and board ordering was not sorted. The ordering of devices was more consistent back then as a result of how configs were processed, but one of the big issues with 1.4 and one of the big reasons that we moved to the 2.0 architecture was to fix the configuration->device instance creation flow and make it so (a) config order shouldn't matter, which it did before, and (b) we can have a device configured that fails and still be okay.

if we need sorting, we can add it in, but I don't think its something we had and then lost from the architecture change.. at least, its not something we had intentionally/by design before.
